# Generated by Django 5.1.4 on 2025-01-13 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время')),
                ('end_time', models.TimeField(verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Смены',
            },
        ),
        migrations.CreateModel(
            name='ShiftUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shift', verbose_name='Смена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Расписание',
            },
        ),
    ]
